### ISSUE TITLE
Error after clicking next on the CriticalQuestions page

### ISSUE THREAD

**Issue by yus252** [instedd/oasis#135]
Based on master(common issue):
```
Error: Objects are not valid as a React child (found: object with keys {loc, msg, type}). If you meant to render a collection of children, use an array instead.
    in p (at CriticalQuestions/index.js:212)
    in CriticalQuestions (created by Context.Consumer)
    in Route (at src/index.js:39)
    in Switch (at src/index.js:34)
    in div (at Wrapper/index.js:22)
    in main (at Wrapper/index.js:20)
    in Wrapper (at src/index.js:33)
    in Router (at src/index.js:29)
    in MuiPickersUtilsProvider (at src/index.js:28)
    in Provider (at src/index.js:27)
```

**Comment by pyritewolf** [comment]
Hello @yus252 ! Could you provide some more info on this issue? Again I wasn't able to reproduce it either locally or on staging.

Like I mentioned [here](https://github.com/instedd/oasis/issues/136#issuecomment-652536171), some logging info might help us find out what's going on.

Specifically for this one, I'd say it would also help a lot to know what you've answered so far in the questionnaire (wether you're sick, tested and the Critical Questions form info) because it's very relevant for this specific interaction!

**Comment by yus252** [comment]
I logged in locally as a guest, clicked on "I Am Not Sick", and then clicked on "No, I Have Not". After filling the critical questions, I clicked on the next button, which is like ">". There, the error happens.

**Comment by pyritewolf** [comment]
I think it might actually be related to what we were chatting in the other issue. Could you check if it's solved after the other one's sorted out? 🙂

**Comment by yus252** [comment]
Yes! You are right. After running ./dev-setup.sh, it works.

**Comment by yus252** [comment]
Which issue are you referring too? Could you please point that out for me?

**Comment by pyritewolf** [comment]
Whelp I thought I'd linked it but I didn't 😅 I meant the #136 - the Sign In one!

**Comment by yus252** [comment]
No, it does not solve the problem as now I click "Continue as a guest", which is not related to login issue. I think it might be related to #129 since I did not fill "Close Contacts" and "Recent Travels".

**Comment by pyritewolf** [comment]
😢 I was really hoping it was related to that one since I couldn't reproduce it here. It sounds like it could be related to #129, but as far as I can remember that one's meant to stop people from submitting half-filled travel information (ie. saying you visited Argentina but never saying when you returned to your home country).

The two things that come to my mind are:

- Do you have the latest from `master`? Ana pushed some fixes to the travels subsystem earlier today, I didn't get to see the error she'd found but it might be related!
- Anything interesting on the `ui` logs?

**Comment by yus252** [comment]
I cloned the master just but the error still exists. Here is the full error:

```
Error: Objects are not valid as a React child (found: object with keys {loc, msg, type}). If you meant to render a collection of children, use an array instead.
    in p (at CriticalQuestions/index.js:177)
    in CriticalQuestions (created by Context.Consumer)
    in Route (at src/index.js:39)
    in Switch (at src/index.js:34)
    in div (at Wrapper/index.js:22)
    in main (at Wrapper/index.js:20)
    in Wrapper (at src/index.js:33)
    in Router (at src/index.js:29)
    in MuiPickersUtilsProvider (at src/index.js:28)
    in Provider (at src/index.js:27)

(anonymous function)
src/actions/story.js:47
  44 |   body: story,
  45 | });
  46 | 
> 47 | dispatch({
     | ^  48 |   type: SAVED_STORY,
  49 |   payload: {
  50 |     status: response.error || { type: SUCCESS },
```

**Comment by yus252** [comment]
./dev-set.sh might help.
