### ISSUE TITLE
Cannot Sign In

### ISSUE THREAD

**Issue by yus252** [instedd/oasis#136]
Based on master(backend issue):
After showing "We're checking your credentials...", it does not jump to the map/story page or show any error message.

**Comment by pyritewolf** [comment]
Hello @yus252 ! Can you provide us with more details on how to reproduce the issue? I was unable to replicate it either locally or in the staging environment while being up-to-date with `master`.

Bear in mind, both the log in & sign up processes are slow (up to 10s) because we've opted for slower but more secure encryption method than the standard, considering it's such a data-sensitive project 😄 

As a footnote, if you've followed [the readme's setup instructions](https://github.com/instedd/oasis#local-project-setup) you should be able to see some messages associated to the issue in the console where you ran `docker-compose up`. Those messages would be very helpful to further understand the issue! If you don't see any messages, you can try opening multiple consoles and lifting the individual containers in each one (doing `docker-compose up db`, `docker-compose up api` and  `docker-compose up ui`). By doing that, you should be able to get some logging info from each section of the app individually (db, backend and frontend respectively!)

**Comment by yus252** [comment]
On the deployed app 1oasis.org, I am able to sign in. However, locally I am using the same username and password but cannot sign in. What happens is that after it says "We're checking your credentials..." it still stays on the sign in page. There is not error message which says wrong username/password/login failed. In the terminal, I saw messages like this:

```
api_1  | FROM stories 
api_1  | WHERE stories.id IS NULL 
api_1  |  LIMIT %(param_1)s) AS anon_1 LEFT OUTER JOIN travels AS travels_1 ON anon_1.stories_id = travels_1.story_id]
api_1  | [parameters: {'param_1': 1}]
api_1  | (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by pyritewolf** [comment]
That log is super useful! Looks like it's a local issue and not a bug in the project 🥳 

I think that you should be able to solve the issue by simply running the third step in the [setup instructions](https://github.com/instedd/oasis#local-project-setup). Just as the instructions point out - it's useful to run that every time you update your master, since the snippet updates tables, packages and other things that may change as the project evolves.

Bear in mind, the DB between 1oasis.org and your development environment is not shared - so you'll need to create an account for your local environment. This is intentional, aimed to ensure that you can test freely without distorting staging data 😄

**Comment by yus252** [comment]
Yes! You are right. After running ./dev-setup.sh, it works.
