### ISSUE TITLE
Git commit failed after creating new db model.

### ISSUE THREAD

**Issue by vinovo** [instedd/oasis#148]
I followed the steps in README.md to create a new model for persisting my story. But seems like I'm failing some of the pre-commit stages that prevent me from committing and pushing. The log is as followed:

> 16:51	Commit failed with error
> 			0 files committed, 6 files failed to commit: Add my_story table
> 			black....................................................................Passed
> 			flake8...................................................................Failed
> 			- hook id: flake8
> 			- exit code: 1
> 			backend/alembic/env.py:8:1: F401 'stories.models as story_models' imported but unused
> 			backend/alembic/env.py:9:1: F401 'users.models as user_models' imported but unused
> 			backend/alembic/env.py:10:1: F401 'mystories.models as mystory_models' imported but unused
> 			prettier.................................................................Passed

It seems like the lines for importing new models in `/backend/alembic/env.py`  are marked as unused import statements. Can someone give me some pointers how to circumvent this? Thanks!

![image](https://user-images.githubusercontent.com/35409183/86672033-18867800-bfab-11ea-8dd1-6df7eb2034f8.png)

**Comment by pyritewolf** [comment]
Hey there! A little context and my thoughts on this one:

- The Alembic setup was done well before we configured precommit
- Precommit only runs on modified files, normally, so it never ran on this one 🤦 
- Alembic however needs these imports here, even if they're not explicitly used - else, the migrations don't work

With that for context, I think adding the file to the ignored list on the [precommit](https://github.com/instedd/oasis/blob/master/.pre-commit-config.yaml#L17) config file should be enough.

As a model design comment, I get the feeling you're trying to add a model that's semantically already there (there's already `stories`, and the addition is `mystories` - stories are already associated to a user, if the person was logged in). I suggest considering if the fields you're storing would not be better suited to add to the `Story` model, or if the new model could have a new name, to avoid confusion in the future!

Happy coding! ☺️

**Comment by vinovo** [comment]
@pyritewolf Thank you very much for the help!

If I were to change the line you mentioned. Will be become something like this, correct?
```
        exclude: >
            (?x)^(
                legacy/|
                backend/emails/contents.py|
                backend/alembic/env.py
            )$ 
```

I tried making that change but it's still not allowing me to commit. Is there other steps i'm missing?

The reason why I added a new `my_stories` table was because I thought there was the need to store multiple 'my story' (a paragraph of text) for a given user and story. Seems like Eliah now tells us to only save one 'my story' for each user. I will double check with that. But if I am to store multiple text for the same user, putting them into rows of new table with foreign keys referencing user id or story id would be a proper practice, wouldn't it? Appreciate it if you can confirm on this! I would definitely try to make a more descriptive name for the table. And thank you again for those explanations!

**Comment by pyritewolf** [comment]
> If I were to change the line you mentioned. Will be become something like this, correct?

Yes, precisely! I'm scratching my head as to why it's not letting you move forward. Is the error message the same?

Bear in mind, when pre-commit runs, it may modify your files with corrections and you have to manually add them to the staging area (`git add (the file's path)` in order for the commit to be considered ok by the process.

> The reason why I added a new my_stories table was because I thought there was the need to store multiple 'my story' (a paragraph of text) for a given user and story.

Ah, makes sense! In that case it would be necessary, yes. If that ends up being the case, I'd suggest maybe `story_testimonials` as a possible name for the model. Also, I'd suggest it being a model within the already existing `story` app, since as far as business logics go it is related to the whole concept of a user's COVID story.

> I just tried updating the pre-commit config file again and it works!

lol I just got to this point of the comment. I'm glad it worked! I'm leaving the explanation I wrote above anyways since it further details the pre-commit process 😄

**Comment by vinovo** [comment]
Oh so would it be something like what we had for story_symptoms, which could be a subclass of Story?

**Comment by pyritewolf** [comment]
Precisely! This is specially helpful because a story may be created without a user and we've solved the whole authentication deal for stories already.

For further context, this is how authentication currently works:
- If you're not logged in and you create a story, we give you an auth cookie that identifies you as the owner of that story
   - You can edit any info related to that story (the story itself, symptoms, etc) but other folks lacking that cookie won't be able to edit it (that's ensured by [this magical line](https://github.com/instedd/oasis/blob/master/backend/router/stories.py#L78) in each protected endpoint)
   - If you log in while you have this cookie, your user will be associated to the story you created anonymously
- If you're logged in, you get a cookie identifying the user and everything's chill

**Comment by vinovo** [comment]
Really appreciate it! The authentication process now makes much more sense to me.

Still having a couple of questions:
1. Does the cookie for anonymous user every expire? Or if the anonymous user use a different browser, is he/she not able to be associated with the story he/she created earlier?
2. Now I have a one-to-many relationship between story and my-story. Would I need to store a list of my-story id in the rows of story table in order to retrieve all related my-story for a user?

**Comment by pyritewolf** [comment]
> Does the cookie for anonymous user every expire?

I believe it's set to expire within 5 days in both staging and production. It's an environment variable called `COOKIE_EXPIRATION_SECONDS`. We went with an expiring cookie because we went pretty intense on the security features for the app, given the sensitive data it handles.

> Or if the anonymous user use a different browser, is he/she not able to be associated with the story he/she created earlier?

Yep, if someone enters their information anonymously in a browser and then go to another browser (say, they switch from mobile to desktop) they'll have to re-upload their data. Again, security before comfort.

> Now I have a one-to-many relationship between story and my-story. Would I need to store a list of my-story id in the rows of story table in order to retrieve all related my-story for a user?

Not really! I'd have to brush up my SQLAlchemy, and it depends on how you specifically wrote the code, but you should be able to fetch something like `user.story.my_stories`. You can look into lazy loading and relationship loading for SQLAlchemy 🕵️  But then again, I suggest you go fetching it by `story` - it's the one thing you know you'll have no matter what at that point in the app. You can reach the dashboard without having a user!

For code references for this you can look into travels, close contacts and story symptoms - a story has many of those. They're loaded on the story itself, but it's easy enough to load them individually if need be 😄 

Feel free to drop any other questions you may get along the way!

**Comment by vinovo** [comment]
Got it, many thanks for all those detailed explanations!!❤️

**Comment by alex-wenzel** [comment]
Reopening because this issue was blocking me from adding my model as well. I think `env.py` should be permanently added to the flake8 ignore list. Unless anyone has any objections to this I'll go ahead and assign to myself and take care of it.
