### ISSUE TITLE
Add map legend on <Dashboard />

### ISSUE THREAD

**Issue by pyritewolf** [instedd/oasis#94]
- [x] Implement the default mapbox legend on the bottom left corner of the `<Dashboard/>`
    - maybe make it dependant on the `draggable` prop? maybe add a `displayLegend` prop that's set by the `<Wrapper/>`? have fun!
- [x] Integrate visually suggestions box with my status
    - remove "my status" title & inline the two existing lines 
- [x] display "latest update" below suggestions & status
- [x] reduce spacing around titles for these boxes (at least on mobile)

**Comment by easpencer** [comment]
Checking again on status of the legend updating based on cloropleth level. Was there going to be a new issue on this?

**Comment by anaPerezGhiglia** [comment]
@easpencer the legend should not be updated depending on the zoom of the cloropleth level since the ranges (of the legend) are always the same. 
This is because since #98 the data is clustered taking into account all the regions information - whether is country or state. This means that the `red-1` (for example) means the same amount of cases whether you see this color in a US-state or in a country

If I didn't explain myself clearly, please let me know and we see it 🙂

**Comment by easpencer** [comment]
Thanks Ana that was my understanding too. However when you zoom in on America where we have more granularity we get some “red” spots in high incidence zones.  These then show up as have 1-2milluon cases which doesn’t make sense.  Am I confusing something? 

E

**Comment by anaPerezGhiglia** [comment]
@easpencer For what you tell me, I believe that the issue is the following:
The us-states layer is on top of the global layer. 
Both layers are being displayed. 
The problem is that the us-states layer does not have the same boundaries than the global layer for US. This ends up with the strong-red (belonging to US as a country) "leaking" and being visible alongside the states

For what I'm seeing, the major problem with the boundaries are the lakes that are near the limits or the bays . Is this what you are seeing? 

<img src="https://user-images.githubusercontent.com/13237343/85636461-06c1de00-b657-11ea-8804-5d113027a141.png" height="50%" width="50%">
